//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int event_id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int reserved_places { get; set; }
        public string photo { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public bool seating { get; set; }
        public string descripcion { get; set; }
        public int establish_id { get; set; }
    
        public virtual Establishment Establishment { get; set; }
    }
}
