//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int message_id { get; set; }
        public Nullable<int> sender_id { get; set; }
        public string content { get; set; }
        public string send_at { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<int> chat_id { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
